version: "3.9"

services:
  db:
    image: postgres:12-alpine
    container_name: db-melody
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    networks:
      - app-melody

  adminer:
    image: adminer
    container_name: adminer-melody
    restart: always
    ports:
      - "1235:8080"
    networks:
      - app-melody

  app:
    build: .
    container_name: app-melody
    restart: always
    ports:
      - "8001:8000"
    env_file:
      - /src/.env
    depends_on:
      - db
    networks:
      - app-melody

networks:
  app-melody: