openapi: 3.0.3
info:
  title: MusicWay. Ear
  description: Спецификация для сервера, который обрабатывает задания на определение на слух.
  version: 1.0.0

tags:
  - name: Settings
    description: Действия с настройками
  - name: Tasks
    description: Действия с упражнениями

paths:
  /api/v1/settings:
    get:
      tags:
        - Settings
      summary: Получение настроек
      description: Получение настроек упражнения.
      parameters:
        - name: role
          in: query
          required: true
          schema:
            type: string
            title: Role
      responses:
        '200':
          description: ОК
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IntervalsSettingResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '500':
          description: Ошибка сервера

  /api/v1/tasks:
    post:
      tags:
        - Tasks
      summary: Генерация упражнений
      description: Генерация одного или нескольких упражнений.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskSetting'
        required: true
      responses:
        '200':
          description: ОК
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/TaskResponse'
                type: array
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '500':
          description: Ошибка сервера

  /api/v1/tasks/check:
    post:
      tags:
        - Tasks
      summary: Проверка ответа пользователя
      description: Проверяет правильно ли выполнено упражнение.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckTask'
        required: true
      responses:
        '200':
          description: ОК
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckTaskResponse'
        '400':
          description: Ошибка в данных, которые отправил пользователь
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '500':
          description: Ошибка сервера

  /api/v1/tasks/get-mark:
    post:
      tags:
        - Tasks
      summary: Расчет баллов за упражнение
      description: Выставляет балл за упражнение.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MarkRequest'
        required: true
      responses:
        '200':
          description: ОК
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMarkTaskResponse'
        '400':
          description: Ошибка в данных, которые отправил пользователь
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '500':
          description: Ошибка сервера

components:
  schemas:
    Answer:
      properties:
        audio_url:
          type: string
          title: Audio Url
        interval:
          type: string
          title: Interval
      type: object
      required:
        - audio_url
        - interval
      title: Answer

    AnswerResponse:
      properties: {}
      type: object
      title: AnswerResponse

    CheckData:
      properties:
        audio_number:
          type: integer
          title: Audio Number
        interval:
          type: string
          title: Interval
      type: object
      required:
        - audio_number
        - interval
      title: CheckData

    CheckTask:
      properties:
        check_data:
          $ref: '#/components/schemas/CheckData'
        answer:
          items:
            $ref: '#/components/schemas/Answer'
          type: array
          title: Answer
      type: object
      required:
        - check_data
        - answer
      title: CheckTask

    CheckTaskResponse:
      properties:
        is_right:
          type: boolean
          title: Is Right
        answer:
          anyOf:
            - $ref: '#/components/schemas/AnswerResponse'
            - type: 'null'
      type: object
      required:
        - is_right
      title: CheckTaskResponse

    Content:
      properties:
        image_url:
          type: string
          title: Image Url
        image_name:
          type: string
          title: Image Name
        audio_urls:
          items:
            type: string
          type: array
          title: Audio Urls
        intervals:
          items:
            type: string
          type: array
          title: Intervals
      type: object
      required:
        - image_url
        - image_name
        - audio_urls
        - intervals
      title: Content

    CreateTaskSetting:
      properties:
        intervals:
          items:
            type: string
          type: array
          title: Intervals
        count:
          anyOf:
            - type: integer
            - type: 'null'
          title: Count
          default: 1
      type: object
      required:
        - intervals
      title: CreateTaskSetting

    GetMarkTaskResponse:
      properties:
        mark:
          type: integer
          example: 1
          title: Mark
      type: object
      required:
        - mark
      title: GetMarkTaskResponse

    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError

    IntervalsSettingResponse:
      properties:
        description:
          type: string
          title: Description
        intervals:
          items:
            type: string
          type: array
          example: ['Все', 'м.2', 'б.2']
          title: Intervals
        is_need_count:
          type: boolean
          title: Is Need Count
      type: object
      required:
        - description
        - intervals
        - is_need_count
      title: IntervalsSettingResponse

    MarkRequest:
      properties:
        check_data:
          $ref: '#/components/schemas/MistakesCount'
        answer:
          items:
            $ref: '#/components/schemas/Answer'
          type: array
          title: Answer
      type: object
      required:
        - check_data
        - answer
      title: MarkRequest

    MistakesCount:
      properties:
        mistakes_count:
          type: integer
          title: Mistakes Count
      type: object
      required:
        - mistakes_count
      title: MistakesCount

    TaskResponse:
      properties:
        condition:
          type: string
          title: Condition
        content:
          $ref: '#/components/schemas/Content'
        answer:
          items:
            $ref: '#/components/schemas/Answer'
          type: array
          title: Answer
        max_mark:
          type: integer
          title: Max Mark
        query:
          anyOf:
            - type: string
            - type: 'null'
          title: Query
      type: object
      required:
        - condition
        - content
        - answer
        - max_mark
      title: TaskResponse

    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
