openapi: 3.0.3
info:
  title: MusicWay. Melody
  description: Спецификация для сервера, которые обрабатывает задания на построение мелодии.
  version: 1.0.0

tags:
  - name: Settings
    description: Действия с настройками
  - name: Tasks
    description: Действия с упражнениями

paths:
  /api/v1/settings:
    get:
      tags:
        - Settings
      summary: Получение настроек
      description: Получение настроек упражнения.
      parameters:
        - name: role
          in: query
          required: true
          schema:
            type: string
            title: Role
      responses:
        '200':
          description: ОК
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MelodySettingResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '500':
          description: Ошибка сервера

  /api/v1/tasks:
    post:
      tags:
        - Tasks
      summary: Генерация упражнений
      description: Генерация одного или нескольких упражнений.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskSetting'
        required: true
      responses:
        '200':
          description: ОК
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/TaskResponse'
                type: array
        '404':
          description: Не найдена мелодия
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '500':
          description: Ошибка сервера

  /api/v1/tasks/check:
    post:
      tags:
        - Tasks
      summary: Проверка ответа пользователя
      description: Проверяет правильно ли выполнено упражнение.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckTask'
        required: true
      responses:
        '200':
          description: ОК
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckTaskResponse'
        '404':
          description: Не найдена мелодия
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '500':
          description: Ошибка сервера

  /api/v1/tasks/get-mark:
    post:
      tags:
        - Tasks
      summary: Расчет баллов за упражнение
      description: Выставляет балл за упражнение.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckTask'
        required: true
      responses:
        '200':
          description: ОК
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMarkTaskResponse'
        '404':
          description: Не найдена мелодия
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '500':
          description: Ошибка сервера

components:
  schemas:
    Answer:
      properties:
        melody:
          type: string
          format: uuid
          title: Melody
      type: object
      required:
        - melody
      title: Answer

    AnswerResponse:
      properties:
        audio_url:
          type: string
          title: Audio Url
        image_url:
          type: string
          title: Image Url
      type: object
      required:
        - audio_url
        - image_url
      title: AnswerResponse

    CheckData:
      properties:
        notes:
          items:
            type: string
          type: array
          title: Notes
      type: object
      required:
        - notes
      title: CheckData

    CheckTask:
      properties:
        check_data:
          $ref: '#/components/schemas/CheckData'
        answer:
          $ref: '#/components/schemas/Answer'
      type: object
      required:
        - check_data
        - answer
      title: CheckTask

    CheckTaskResponse:
      properties:
        is_right:
          type: boolean
          title: Is Right
        answer:
          $ref: '#/components/schemas/AnswerResponse'
      type: object
      required:
        - is_right
        - answer
      title: CheckTaskResponse

    Content:
      properties:
        initial_note:
          type: string
          title: Initial Note
        intervals:
          items:
            type: string
          type: array
          title: Intervals
      type: object
      required:
        - initial_note
        - intervals
      title: Content

    CreateTaskSetting:
      properties:
        melodies:
          items:
            type: string
            format: uuid
          type: array
          title: Melodies
      type: object
      required:
        - melodies
      title: CreateTaskSetting

    GetMarkTaskResponse:
      properties:
        mark:
          type: integer
          example: 7
          title: Mark
      type: object
      required:
        - mark
      title: GetMarkTaskResponse

    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError

    MelodyResponse:
      properties:
        id:
          type: string
          format: uuid
          title: Id
        name:
          type: string
          title: Name
      type: object
      required:
        - id
        - name
      title: MelodyResponse

    MelodySettingResponse:
      properties:
        description:
          anyOf:
            - type: string
            - type: 'null'
          title: Description
        melodies:
          anyOf:
            - items:
                $ref: '#/components/schemas/MelodyResponse'
              type: array
            - type: 'null'
          title: Melodies
        is_need_count:
          type: boolean
          title: Is Need Count
      type: object
      required:
        - description
        - melodies
        - is_need_count
      title: MelodySettingResponse

    TaskResponse:
      properties:
        condition:
          type: string
          title: Condition
        content:
          $ref: '#/components/schemas/Content'
        answer:
          $ref: '#/components/schemas/Answer'
        max_mark:
          type: integer
          title: Max Mark
        query:
          type: string
          title: Query
      type: object
      required:
        - condition
        - content
        - answer
        - max_mark
        - query
      title: TaskResponse

    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
