"""not null block

Revision ID: d19e921f3027
Revises: e29389716beb
Create Date: 2025-03-14 23:06:02.749358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import storage.file_type


# revision identifiers, used by Alembic.
revision: str = 'd19e921f3027'
down_revision: Union[str, None] = 'e29389716beb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('homework', 'block_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('homework', 'block_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
