"""not null url

Revision ID: 4b39a303dfe5
Revises: 2151a680cab6
Create Date: 2025-03-15 16:24:58.406883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import storage.file_type


# revision identifiers, used by Alembic.
revision: str = '4b39a303dfe5'
down_revision: Union[str, None] = '2151a680cab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_type', 'service_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_type', 'service_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
