"""number material not null

Revision ID: 0267a1652ad8
Revises: 597fc767c41f
Create Date: 2025-03-15 18:27:05.596937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import storage.file_type


# revision identifiers, used by Alembic.
revision: str = '0267a1652ad8'
down_revision: Union[str, None] = '597fc767c41f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_material', 'number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_material', 'number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
