"""change len note

Revision ID: 4f2b1351bb91
Revises: bbf2745a291b
Create Date: 2025-03-27 21:16:36.633097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f2b1351bb91'
down_revision: Union[str, None] = 'bbf2745a291b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audio', 'notes',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=5)),
               type_=postgresql.ARRAY(sa.String(length=15)),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audio', 'notes',
               existing_type=postgresql.ARRAY(sa.String(length=15)),
               type_=postgresql.ARRAY(sa.VARCHAR(length=5)),
               existing_nullable=False)
    # ### end Alembic commands ###
