"""add GIN

Revision ID: da953ebb724d
Revises: 9b4965da11d1
Create Date: 2025-03-05 21:35:50.747244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import storage.file_type
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da953ebb724d'
down_revision: Union[str, None] = '9b4965da11d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_material', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=False))
    op.create_index('study_materials_search_idx', 'study_material', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('study_materials_search_idx', table_name='study_material', postgresql_using='gin')
    op.drop_column('study_material', 'search_vector')
    # ### end Alembic commands ###
