"""nullable video

Revision ID: e39102b576e7
Revises: 0267a1652ad8
Create Date: 2025-03-25 00:12:48.543133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import storage.file_type


# revision identifiers, used by Alembic.
revision: str = 'e39102b576e7'
down_revision: Union[str, None] = '0267a1652ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_material', 'video_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_material', 'video_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
