"""cascade delete

Revision ID: 597fc767c41f
Revises: 4b39a303dfe5
Create Date: 2025-03-15 18:23:05.314829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import storage.file_type


# revision identifiers, used by Alembic.
revision: str = '597fc767c41f'
down_revision: Union[str, None] = '4b39a303dfe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('homework_task_homework_id_fkey', 'homework_task', type_='foreignkey')
    op.create_foreign_key(None, 'homework_task', 'homework', ['homework_id'], ['id'], ondelete='CASCADE')
    op.add_column('study_material', sa.Column('number', sa.Integer(), nullable=True))
    op.alter_column('task', 'material_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'material_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('study_material', 'number')
    op.drop_constraint(None, 'homework_task', type_='foreignkey')
    op.create_foreign_key('homework_task_homework_id_fkey', 'homework_task', 'homework', ['homework_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
