"""rename user field

Revision ID: d93890097dcc
Revises: a1a1b9532a0a
Create Date: 2025-04-19 17:42:20.273274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import storage.file_type


# revision identifiers, used by Alembic.
revision: str = 'd93890097dcc'
down_revision: Union[str, None] = 'a1a1b9532a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_changed_password', sa.Boolean(), nullable=False))
    op.drop_column('user', 'is_first_login')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_first_login', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'is_changed_password')
    # ### end Alembic commands ###
