"""init

Revision ID: a1a1b9532a0a
Revises: 
Create Date: 2025-04-10 23:29:29.403503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import storage.file_type
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1a1b9532a0a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('topic_block',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_url', storage.file_type.FileType('blocks'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('study_material',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('video_url', storage.file_type.FileType('materials'), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('russian', name || ' ' || text)", persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['topic_block.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('study_materials_search_idx', 'study_material', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('task_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('service_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['topic_block.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('service_url')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('patronymic', sa.String(length=100), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('is_first_login', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['study_material.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_class',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_number', sa.Integer(), nullable=False),
    sa.Column('week_day', sa.String(length=20), nullable=False),
    sa.Column('class_time', sa.Time(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('student_description', sa.Text(), nullable=False),
    sa.Column('teacher_description', sa.Text(), nullable=False),
    sa.Column('image_url', storage.file_type.FileType('variants'), nullable=False),
    sa.Column('demo_url', storage.file_type.FileType('variants'), nullable=False),
    sa.ForeignKeyConstraint(['task_type_id'], ['task_type.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('homework',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['topic_block.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['learning_class.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_class',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['learning_class.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=True),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('max_mark', sa.Integer(), nullable=False),
    sa.Column('is_study_task', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['study_material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['variant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homework_task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('homework_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('mark', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['homework_id'], ['homework.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homework_task')
    op.drop_table('task')
    op.drop_table('student_class')
    op.drop_table('homework')
    op.drop_table('variant')
    op.drop_table('learning_class')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('task_type')
    op.drop_index('study_materials_search_idx', table_name='study_material', postgresql_using='gin')
    op.drop_table('study_material')
    op.drop_table('topic_block')
    op.drop_table('role')
    # ### end Alembic commands ###
