"""add sevice_url

Revision ID: 2151a680cab6
Revises: d19e921f3027
Create Date: 2025-03-15 16:23:18.498470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import storage.file_type


# revision identifiers, used by Alembic.
revision: str = '2151a680cab6'
down_revision: Union[str, None] = 'd19e921f3027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_type', sa.Column('service_url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'task_type', ['service_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_type', type_='unique')
    op.drop_column('task_type', 'service_url')
    # ### end Alembic commands ###
