"""change len notes

Revision ID: 70c0bfe8ff22
Revises: 4f2b1351bb91
Create Date: 2025-04-12 17:39:10.151859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70c0bfe8ff22'
down_revision: Union[str, None] = '4f2b1351bb91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audio', 'notes',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=15)),
               type_=postgresql.ARRAY(sa.String(length=50)),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audio', 'notes',
               existing_type=postgresql.ARRAY(sa.String(length=50)),
               type_=postgresql.ARRAY(sa.VARCHAR(length=15)),
               existing_nullable=False)
    # ### end Alembic commands ###
