"""change flag variant

Revision ID: 41de489e589a
Revises: 86d2811fe972
Create Date: 2025-05-03 15:31:11.473582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import storage.file_type


# revision identifiers, used by Alembic.
revision: str = '41de489e589a'
down_revision: Union[str, None] = '86d2811fe972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variant', sa.Column('for_homework', sa.Boolean(), nullable=False, server_default=str(True)))
    op.drop_column('variant', 'is_training_only')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variant', sa.Column('is_training_only', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('variant', 'for_homework')
    # ### end Alembic commands ###
