"""add is_training_only

Revision ID: 86d2811fe972
Revises: d93890097dcc
Create Date: 2025-05-03 15:21:49.486441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import storage.file_type


# revision identifiers, used by Alembic.
revision: str = '86d2811fe972'
down_revision: Union[str, None] = 'd93890097dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variant', sa.Column('is_training_only', sa.Boolean(), nullable=False, server_default=str(False)))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variant', 'is_training_only')
    # ### end Alembic commands ###
