"""add block to hw

Revision ID: e29389716beb
Revises: da953ebb724d
Create Date: 2025-03-14 23:05:05.824118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import storage.file_type


# revision identifiers, used by Alembic.
revision: str = 'e29389716beb'
down_revision: Union[str, None] = 'da953ebb724d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homework', sa.Column('block_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'homework', 'topic_block', ['block_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'homework', type_='foreignkey')
    op.drop_column('homework', 'block_id')
    # ### end Alembic commands ###
