"""add other tables

Revision ID: 782750e3af76
Revises: ac8fcb0760fc
Create Date: 2025-03-02 22:23:42.451456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import storage.file_type
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '782750e3af76'
down_revision: Union[str, None] = 'ac8fcb0760fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic_block.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('variant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('student_description', sa.Text(), nullable=False),
    sa.Column('teacher_description', sa.Text(), nullable=False),
    sa.Column('image_url', storage.file_type.FileType(), nullable=False),
    sa.Column('demo_url', storage.file_type.FileType(), nullable=False),
    sa.ForeignKeyConstraint(['task_type_id'], ['task_type.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('homework',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['learning_class.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('max_mark', sa.Integer(), nullable=False),
    sa.Column('is_study_task', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['study_material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['variant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homework_task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('homework_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('mark', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['homework_id'], ['homework.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('user', 'surname',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('user', 'patronymic',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('user', 'patronymic',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('user', 'surname',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_table('homework_task')
    op.drop_table('task')
    op.drop_table('homework')
    op.drop_table('variant')
    op.drop_table('task_type')
    # ### end Alembic commands ###
