"""rename topic to block

Revision ID: 9b4965da11d1
Revises: 782750e3af76
Create Date: 2025-03-05 18:09:11.415805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import storage.file_type


# revision identifiers, used by Alembic.
revision: str = '9b4965da11d1'
down_revision: Union[str, None] = '782750e3af76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_material', sa.Column('block_id', sa.UUID(), nullable=False))
    op.drop_constraint('study_material_topic_id_fkey', 'study_material', type_='foreignkey')
    op.create_foreign_key(None, 'study_material', 'topic_block', ['block_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('study_material', 'topic_id')
    op.add_column('task_type', sa.Column('block_id', sa.UUID(), nullable=False))
    op.drop_constraint('task_type_topic_id_fkey', 'task_type', type_='foreignkey')
    op.create_foreign_key(None, 'task_type', 'topic_block', ['block_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('task_type', 'topic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_type', sa.Column('topic_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'task_type', type_='foreignkey')
    op.create_foreign_key('task_type_topic_id_fkey', 'task_type', 'topic_block', ['topic_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('task_type', 'block_id')
    op.add_column('study_material', sa.Column('topic_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'study_material', type_='foreignkey')
    op.create_foreign_key('study_material_topic_id_fkey', 'study_material', 'topic_block', ['topic_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('study_material', 'block_id')
    # ### end Alembic commands ###
